### ISSUE TITLE
Mouse doesn't seem to work

### ISSUE THREAD

**Issue by billybonks** [noraesae/koko#16]
The mouse was working then i made koko.yml and it stopped working.

```
app:
  scrollback-limit: 20000
  root-channel-name: '$'


user:
  nick: octocat
  username: octocat
  realname: octocat

servers:
  - name: Mozilla
    host: irc.mozilla.org
    port: 6667
  - name: Freenode
    host: irc.freenode.net
    port: 6667
~
````
